version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWD
      PGUSER: $DB_USER
      PGPORT: $DB_PORT
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - ./database-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: "pg_isready -h db"
      timeout: 10s
      retries: 10
volumes:
  database-data: