name: client

on:
  workflow_dispatch:
  push:
    branches:
      - release
    paths:
      - client/**

env:
  IMAGE_NAME: djenerate-client

jobs:
  push:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v2

      - name: build image
        run: |
          docker build . --file Dockerfile --build-arg VITE_SPOTIFY_CLIENT_ID=${{secrets.VITE_SPOTIFY_CLIENT_ID}} --build-arg VITE_SPOTIFY_REDIRECT_URI=${{secrets.VITE_SPOTIFY_REDIRECT_URI}} --tag $IMAGE_NAME
      - name: login to ghcr
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u catherine-sun --password-stdin

      - name: push image to ghcr
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 35.232.50.39
          username: mailcatherines
          key: ${{ secrets.KEY }}
          script: |
            docker compose down
            docker compose pull && docker compose up -d